/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.File;
import javax.swing.ToolTipManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import utiles.HelpMessages;
import utiles.ProcessController;

/**
 *
 * @author XPC
 */
public class FileReader_view extends javax.swing.JFrame {

    public File file;
    public int n;
    private Principal_view princ_v;
    
    public FileReader_view(Principal_view princ_v) {
        this.princ_v = princ_v;
        initComponents();
        this.setDefaultCloseOperation(0);
        this.help_messages();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        jFileChooser1.setFileFilter(filter);
    }

    public void help_messages(){
        this.setHelpMessage(n_help, HelpMessages.N_COMMAND_HELP.message);
        this.setHelpMessage(file_help, HelpMessages.FILE_READER_HELP.message);
    }
    
     public void setHelpMessage(javax.swing.JComponent element, String message){
        ToolTipManager.sharedInstance().setDismissDelay(60000);
        element.setToolTipText(message);
        element.setEnabled(false);
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        file_help = new javax.swing.JButton();
        n_help = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        Cancelar = new javax.swing.JButton();
        run_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        N_label = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 220, 220));

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));
        jPanel1.setForeground(new java.awt.Color(220, 220, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file_help.setIcon(new javax.swing.ImageIcon("E:\\User\\Documentos\\Semestres\\S1 - 2021\\SO\\Proyecto 1\\Proyecto 1\\message_system\\src\\Imagenes\\help_icon.png")); // NOI18N
        file_help.setMargin(new java.awt.Insets(0, 0, 0, 0));
        file_help.setMaximumSize(new java.awt.Dimension(0, 0));
        file_help.setMinimumSize(new java.awt.Dimension(0, 0));
        file_help.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.add(file_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 30));

        n_help.setIcon(new javax.swing.ImageIcon("E:\\User\\Documentos\\Semestres\\S1 - 2021\\SO\\Proyecto 1\\Proyecto 1\\message_system\\src\\Imagenes\\help_icon.png")); // NOI18N
        n_help.setMargin(new java.awt.Insets(0, 0, 0, 0));
        n_help.setMaximumSize(new java.awt.Dimension(0, 0));
        n_help.setMinimumSize(new java.awt.Dimension(0, 0));
        n_help.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.add(n_help, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 30, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cantidad de comandos para parar: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, -1));

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\XPC\\Desktop\\desktop.ini"));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 680, 340));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        run_button.setText("Correr comandos");
        run_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(run_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 140, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lector de archivo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        N_label.setText("0");
        N_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_labelActionPerformed(evt);
            }
        });
        jPanel1.add(N_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        Principal_view princ = princ_v;
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        int returnVal = jFileChooser1.showOpenDialog(jFileChooser1);
        if (returnVal == jFileChooser1.APPROVE_OPTION) {
            this.file = jFileChooser1.getSelectedFile();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void run_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_buttonActionPerformed
        //SI NO SELECCIONA ARCHIVO DARLE ERROR *********************************
        princ_v.setN_command(Integer.parseInt(this.N_label.getText()));
        princ_v.setCommand__file(this.file);
        Principal_view princ = princ_v;
        princ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_run_buttonActionPerformed

    private void N_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_labelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_labelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileReader_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileReader_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileReader_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileReader_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField N_label;
    private javax.swing.JButton file_help;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n_help;
    private javax.swing.JButton run_button;
    // End of variables declaration//GEN-END:variables
}
